const LESSONS = {

  1: [
    { arabic: "بَيْتٌ", german: "ein Haus"},
    { arabic: "مَسْجِدٌ", german: "eine Moschee"},
    { arabic: "بَابٌ", german: "eine Tür"},
    { arabic: "كِتَابٌ", german: "ein Buch"},
    { arabic: "قَلَمٌ", german: "ein Stift"},
    { arabic: "مِفْتَاحٌ", german: "ein Schlüssel"},
    { arabic: "مَكْتَبٌ", german: "ein Schreibtisch, ein Burö (nach Lektion 7)"},
    { arabic: "سَرِيرٌ", german: "ein Bett"},
    { arabic: "كُرْسِيٌّ", german: "ein Stuhl"},
    { arabic: "نَجْمٌ", german: "ein Stern"},
    { arabic: "قَمِيصٌ", german: "ein Hemd"},
    { arabic: "طَبِيبٌ", german: "ein Arzt"},
    { arabic: "نَعَمْ", german: "ja"},
    { arabic: "أَ", german: "Fragepartikel (vor Entscheidungsfragen, direkt vor dem Folgewort)"},
    { arabic: "وَ", german: "und (direkt vor dem Folgewort)"},
    { arabic: "وَلَدٌ", german: "ein Junge"},
    { arabic: "طَالِبٌ", german: "ein Student"},
    { arabic: "رَجُلٌ", german: "ein Mann"},
    { arabic: "تَاجِرٌ", german: "ein Händler"},
    { arabic: "كَلْبٌ", german: "ein Hund"},
    { arabic: "قِطٌّ", german: "ein Kater"},
    { arabic: "حِمَارٌ", german: "ein Esel"},
    { arabic: "حِصَانٌ", german: "ein Pferd"},
    { arabic: "جَمَلٌ", german: "ein Kamel"},
    { arabic: "دِيكٌ", german: "ein Hahn"},
    { arabic: "مُدَرِّسٌ", german: "ein Lehrer"},
    { arabic: "مِنْدِيلٌ", german: "ein Tuch (auch: Papiertaschentuch oder Serviette)"},
    { arabic: "لَا", german: "nein"},
    { arabic: "مَا", german: "was"},
  ],

  2: [
    { arabic: "إِمَامٌ", german: "ein Imam"},
    { arabic: "سُكَّرٌ", german: "Zucker"},
    { arabic: "حَجَرٌ", german: "ein Stein"},
    { arabic: "لَبَنٌ", german: "eine Milch"},
  ],

  3: [
    { arabic: "غَنِيٌّ", german: "reich"},
    { arabic: "فَقِيرٌ", german: "arm"},
    { arabic: "طَوِيلٌ", german: "groß (lang)"},
    { arabic: "قَصِيرٌ", german: "kurz"},
    { arabic: "بَارِدٌ", german: "kalt"},
    { arabic: "حَارٌّ", german: "heiß"},
    { arabic: "جَالِسٌ", german: "sitzend"},
    { arabic: "وَاقِفٌ", german: "stehend"},
    { arabic: "جَدِيدٌ", german: "neu"},
    { arabic: "قَدِيمٌ", german: "alt"},
    { arabic: "قَرِيبٌ", german: "nah"},
    { arabic: "بَعِيدٌ", german: "fern"},
    { arabic: "نَظِيفٌ", german: "sauber"},
    { arabic: "وَسِخٌ", german: "schmutzig"},
    { arabic: "صَغِيرٌ", german: "klein"},
    { arabic: "كَبِيرٌ", german: "groß"},
    { arabic: "خَفِيفٌ", german: "leicht (im Sinne des Gewichtes)"},
    { arabic: "ثَقِيلٌ", german: "schwer"},
    { arabic: "الْوَرَقُ", german: "das Papier"},
    { arabic: "الْمَاءُ", german: "das Wasser"},
    { arabic: "التُّفَاحُ", german: "die Äpfel"},
    { arabic: "جَمِيلٌ", german: "schön"},
    { arabic: "الدُّكَّانُ", german: "das Geschäft"},
    { arabic: "حُلْوٌ", german: "süß"},
    { arabic: "مَرِيضٌ", german: "krank"},
    { arabic: "مكْسُوْرٌ", german: "kaputt, gebrochen"},
    { arabic: "المهندس", german: "der Ingenieur"},
    { arabic: "مُفْتاحٌ", german: "offen"},
    { arabic: "لذيذٌ", german: "lecker"},
    { arabic: "سَاعَةٌ ", german: "eine Uhr"},
    { arabic: "تُفَّاحَةٌ ", german: "ein Apfel"},
    { arabic: "التُّفَّاحَةُ ", german: "der Apfel"},
  
  ],

  4: [
    { arabic: "أَيْنَ", german: "wo"},
    { arabic: "عَلَى", german: "auf"},
    { arabic: "غُرْفَةٌ", german: "ein Zimmer"},
    { arabic: "السَّمَاءُ", german: "der Himmel"},
    { arabic: "الْحَمَّامُ", german: "das Badezimmer"},
    { arabic: "الْفَصْلُ", german: "das Klassenzimmer"},
    { arabic: "الْمَطْبَخُ", german: "die Küche"},
    { arabic: "الْمِرْحَاضُ", german: "die Toilette"},
    { arabic: "فِي", german: "in"},
    { arabic: "مِنْ", german: "von (wenn الـ nachfolgt, wird es zu مِنَ)"},
    { arabic: "إِلَى", german: "nach"},
    { arabic: "الْفِلِبِّينُ", german: "Philippinen"},
    { arabic: "الْيَابَانُ", german: "Japan"},
    { arabic: "الْمَدْرَسَةُ", german: "die Schule"},
    { arabic: "الصِّينُ", german: "China"},
    { arabic: "السُّوقُ", german: "der Markt"},
    { arabic: "الْهِنْدُ", german: "Indien"},
    { arabic: "الْجَامِعَةُ", german: "die Universität"},
    { arabic: "الْمُدِيرُ", german: "der Direktor"},
    { arabic: "ذَهَبَ", german: "Er ist gegangen"},
    { arabic: "خَرَجَ", german: "Er ist hinaus gegangen"}
  ],

  5: [
    { arabic: "الرَّسُولُ", german: "der Gesandte"},
    { arabic: "تَحْتَ", german: "unter"},
    { arabic: "الْعَمُّ", german: "der Onkel (Bruder des Vaters)"},
    { arabic: "الِابْنُ", german: "der Sohn"},
    { arabic: "الشَّارِعُ", german: "die Straße"},
    { arabic: "السَّيَّارَةُ", german: "das Auto"},
    { arabic: "الْكَعْبَةُ", german: "die Kaaba"},
    { arabic: "هُنَا", german: "hier"},
    { arabic: "الْخَالُ", german: "der Onkel (Bruder der Mutter)"},
    { arabic: "هُنَاكَ", german: "dort"},
    { arabic: "مُغْلَق", german: "verschlossen, geschlossen"},
    { arabic: "الْبِنْتُ", german: "die Tochter, das Mädchen"},
    { arabic: "الِاسْمُ", german: "der Name"},
    { arabic: "الطَّبِيبُ", german: "der Arzt"},
    { arabic: "الْحَقِيبَةُ", german: "die Tasche, der Rucksack"},
  ],

  6: [
    { arabic: "يَدٌ", german: "eine Hand"},
    { arabic: "رِجْلٌ", german: "ein Bein"},
    { arabic: "عَيْنٌ", german: "ein Auge"},
    { arabic: "أُذُنٌ", german: "ein Ohr"},
    { arabic: "رَأْسٌ", german: "ein Kopf"},
    { arabic: "أَنْفٌ", german: "eine Nase"},
    { arabic: "فَمٌ", german: "ein Mund"},
    { arabic: "وَجْهٌ", german: "ein Gesicht"},
    { arabic: "الْمِكْوَاةُ", german: "das Bügeleisen"},
    { arabic: "الْأَنْفُ", german: "die Nase"},
    { arabic: "الْبَقَرَةُ", german: "die Kuh"},
    { arabic: "الْفَمُ", german: "der Mund"},
    { arabic: "الدَّرَّاجَةُ", german: "das Fahrrad"},
    { arabic: "الْقِدْرُ", german: "der Kochtopf"},
    { arabic: "الْمِلْعَقَةُ", german: "der Löffel"},
    { arabic: "الْأُذُنُ", german: "das Ohr"},
    { arabic: "الْفَلَّاحُ", german: "der Bauer"},
    { arabic: "الْعَيْنُ", german: "das Auge"},
    { arabic: "الْأُمُّ", german: "die Mutter"},
    { arabic: "الْيَدُ", german: "die Hand"},
    { arabic: "الْأَبُ", german: "der Vater"},
    { arabic: "الرِّجْلُ", german: "das Bein"},
    { arabic: "الثَّلَّاجَةُ", german: "der Kühlschrank"},
    { arabic: "سَرِيعٌ", german: "schnell"},
    { arabic: "الشَّايُ", german: "der Tee"},
    { arabic: "النَّافِذَةُ", german: "das Fenster"},
    { arabic: "الْمَغْرِبُ", german: "der Westen"},
    { arabic: "الشَّرْقُ", german: "der Osten"},
    { arabic: "الْقَهْوَةُ", german: "der Kaffee"},
    { arabic: "أَيْضاً", german: "auch"},
    { arabic: "جِدّاً", german: "sehr"},
    { arabic: "لِمَنْ", german: "wessen oder wem gehört"},
    { arabic: "لِـ", german: "gehören, besitzen, für"},
    { arabic: "شَمْسٌ ", german: "eine Sonne"},
    { arabic: "مُسْلِمٌ ", german: "ein Muslim"}
    ],

  7:[
    { arabic: "تِلْكَ", german: "das, jenes (weibliche Form von ذَلِكَ)"},
    { arabic: "النَّاقَةُ", german: "die Kamelstute"},
    { arabic: "الْبَيْضَةُ", german: "das Ei"},
    { arabic: "الْبَطَّةُ", german: "die Ente"},
    { arabic: "الْمُؤَذِّنُ", german: "der Muezzin"},
    { arabic: "الْمُمَرِّضَةُ", german: "die Krankenschwester"},
    { arabic: "الدَّجَاجَةُ", german: "die Henne"}
    ],

  8: [
    { arabic: "أَمْرِيكَا", german: "Amerika"},
    { arabic: "السِّكِّينُ", german: "das Messer"},
    { arabic: "مُغْلَقٌ", german: "geschlossen, verschlossen"},
    { arabic: "أَلْمَانِيَا", german: "Deutschland"},
    { arabic: "العِرَاقُ", german: "der Irak"},
    { arabic: "إِنْكِلْتِرَا", german: "England"},
    { arabic: "سُوِيسرَا", german: "Schweiz"},
    { arabic: "المُسْتَشْفَى", german: "das Krankenhaus"},
    { arabic: "خَلْفَ", german: "hinter"},
    { arabic: "أَمَامَ", german: "vor"},
    { arabic: "جَلَسَ", german: "er saß"}
    ],

  9: [
    { arabic: "الفَاكِهَةُ", german: "das Obst"},
    { arabic: "الإِنْكِلِيزِيَّةُ", german: "Englisch"},
    { arabic: "العُصْفُورُ", german: "der Spatz (kleiner Vogel)"},
    { arabic: "صَعْبٌ", german: "schwierig"},
    { arabic: "الطَّائِرُ", german: "der Vogel (allgemein)"},
    { arabic: "المَدِينَةُ", german: "die Stadt"},
    { arabic: "العَرَبِيَّةُ", german: "Arabisch"},
    { arabic: "القَاهِرَةُ", german: "Kairo"},
    { arabic: "اللُّغَةُ", german: "die Sprache"},
    { arabic: "اليَوْمَ", german: "heute"},
    { arabic: "سَهْلٌ", german: "leicht (im Sinne der Komplextität)"},
    { arabic: "لِمَاذَا", german: "warum"},
    { arabic: "مُجْتَهِدٌ", german: "fleißig"},
    { arabic: "الكُوبُ", german: "die Tasse, der Becher"},
    { arabic: "شَهِيرٌ", german: "berühmt"},
    { arabic: "الْمَكْتَبَةُ", german: "die Bücherei, der Buchladen"},
    { arabic: "الثَّانَوِيَّةُ", german: "die Oberstufe, Oberschule"},
    { arabic: "الآنَ", german: "jetzt"},
    { arabic: "الْوَزِيرُ", german: "der Minister"},
    { arabic: "هُنَاكَ", german: "dort (hinten)"},
    { arabic: "حَادٌّ", german: "scharf (bei Klingen u. ä.)"},
    { arabic: "الْمُسْتَوْصَفُ", german: "die Klinik, das kleine Krankenhaus"},
    { arabic: "السُّوقُ", german: "der Markt"},
    { arabic: "الْمِرْوَحَةُ", german: "der Ventilator"},
    { arabic: "إِنْدُونِيسِيَا", german: "Indonesien"},
    { arabic: "الْكُوَيْتُ", german: "Kuwait"},
    { arabic: "الشَّارِعُ", german: "die Straße"},
    { arabic: "عِنْدَ", german: "mit, bei"},
    { arabic: "الَّذِي", german: "der, welcher"},
    { arabic: "فَرَنْسَا", german: "Frankreich"},
    { arabic: "السَّبُّورَةُ", german: "die Tafel"},
    { arabic: "الْمِحْرَابُ", german: "die Mihrab (Gebetsnische)"},
    { arabic: "الْيَوْمُ", german: "der Tag"},
    { arabic: "كَسْلَانُ", german: "faul"},
    { arabic: "جَوْعَانُ", german: "hungrig"},
    { arabic: "عَطْشَانُ", german: "durstig"},
    { arabic: "غَضْبَانُ", german: "ärgerlich"},
    { arabic: "مَلآنُ", german: "voll"}
    ],

    10: [
      { arabic: "أَخُوكَ", german: "dein Bruder"},
      { arabic: "كِتَابُكَ", german: "dein Buch"},
      { arabic: "كِتَابُهُ", german: "sein Buch"},
      { arabic: "كِتَابُهَا", german: "ihr Buch"},
      { arabic: "كِتَابِي", german: "mein Buch"},
      { arabic: "أَبُوهُ", german: "sein Vater"},
      { arabic: "أَخِي", german: "mein Bruder"},
      { arabic: "أَبِي", german: "mein Vater"},
      { arabic: "لَكَ", german: "gehört dir"},
      { arabic: "لَهُ", german: "gehört ihm"},
      { arabic: "لَهَا", german: "gehört ihr"},
      { arabic: "لِي", german: "gehört mir"},
      { arabic: "ذَهَبْتُ", german: "ich ging"},
      { arabic: "ذَهَبْتَ", german: "du gingst"},
      { arabic: "مَعَ", german: "mit"},
      { arabic: "بِ", german: "an, in"},
      { arabic: "بِالْجَامِعَةِ", german: "an der Universität"},
      { arabic: "الزَّمِيلُ", german: "der Kollege, der Mitschüler"},
      { arabic: "الفَتَى", german: "der junge Mann"},
      { arabic: "الزَّوْجُ", german: "der Ehegatte"},
      { arabic: "وَاحِدٌ", german: "eins"},
      { arabic: "الطِفْلُ", german: "das Kind"},
      { arabic: "مَا", german: "was, keine/nicht (als Verneinung)"},
    ],

    11: [
      { arabic: "فِيهِ", german: "darin" },
      { arabic: "أُحِبُّ", german: "ich mag, ich liebe" },
      { arabic: "مَاذَا", german: "was (eindeutiges Fragewort, im Gegensatz zu مَا, das auch 'nicht' bedeuten kann)" },
    ],

    12: [
      { arabic: "أَنْتِ", german: "du (weiblich)"},
      { arabic: "كِ", german: "besitzanzeigende Endung 'dein' bei weiblich Angesprochenen (Kasra, z. B. بَيْتُكِ)"},
      { arabic: "ذَهَبَتْ", german: "sie ging"},
      { arabic: "الَّتِي", german: "die, welche (Relativpronomen, feminin Singular)"},
      { arabic: "الْعَمُّ", german: "der Onkel (väterlicherseits)"},
      { arabic: "الشَّجَرَةُ", german: "der Baum"},
      { arabic: "الْعَمَّةُ", german: "die Tante (väterlicherseits)"},
      { arabic: "سُورِيَا", german: "Syrien"},
      { arabic: "الْخَالُ", german: "der Onkel (mütterlicherseits)"},
      { arabic: "الْمَدْرَسَةُ الْمُتَوَسِّطَةُ", german: "die Mittelschule"},
      { arabic: "الْخَالَةُ", german: "die Tante (mütterlicherseits)"},
      { arabic: "الْمُفَتِّشُ", german: "der Inspektor"},
      { arabic: "مُسْتَشْفَى الْوِلَادَةِ", german: "das Entbindungsheim"},
      { arabic: "الْفَتَاةُ", german: "die junge Frau"},
      { arabic: "يَا سَيِّدِي", german: "mein Herr!"},
      { arabic: "الدَّفْتَرُ", german: "das Heft"},
      { arabic: "يَا سَيِّدَتِي", german: "meine Dame!"},
      { arabic: "مَالِيزِيَا", german: "Malaysia"},
      { arabic: "كَيْفَ حَالُكَ؟", german: "Wie geht es dir? / Wie geht es Ihnen?"},
      { arabic: "أَنَا بِخَيْرٍ", german: "Mir geht es gut."},
      { arabic: "أُمَّهَاتٌ", german: "Mütter (Plural von أُمٌّ)"},
      { arabic: "آبَاءٌ", german: "Väter (Plural von أَبٌ)"},
      { arabic: "وُزَرَاءُ", german: "Minister (Plural von وَزِيرٌ)"},
      { arabic: "عُلَمَاءُ", german: "Gelehrte (Plural von عَالِمٌ)"},
      { arabic: "أَقْوِيَاءُ", german: "Starke (Plural von قَوِيٌّ)"},
      { arabic: "ضُعَفَاءُ", german: "Schwache (Plural von ضَعِيفٌ)"},
      { arabic: "بَعْدَ", german: "nach (das folgende Substantiv steht im Genitiv)"},
      { arabic: "الْمَمْلَكَةُ الْعَرَبِيَّةُ السُّعُودِيَّةُ", german: "das Königreich Saudi-Arabien"},
    ],

  Grammatik: [
    { arabic: "تَنْوِين", german: "die Unbestimmtheit (hinsichtlich der Wortform)"},
    { arabic: "نَكِرَة", german: "unbestimmt (hinsichtlich der Grammatik)"},
    { arabic: "مَعْرِفَة", german: "bestimmt"},
    { arabic: "اسْمُ إِشَارَة", german: "Demonstrativpronomen"},
    { arabic: "مَعْرِفَة", german: "bestimmt"},
    { arabic: "لَامُ التَّعْرِيف", german: "die bestimmten Artikel"},
    { arabic: "جُمْلَة اسْمِيَّة" , german: "Nominalsatz"},
    { arabic: "حُرُوفُ الْجَر", german: "Präpositionen"},
    { arabic: "مَرْفُوع", german: "Nominativ"},
    { arabic: "مَجْرُور", german: "Genetiv"},
    { arabic: "اسْم", german: "Nomen"},
    { arabic: "فِعْل", german: "Verben"},
    { arabic: "حَرْف", german: "Partikel"},
    { arabic: "الْخَبَر", german: "Satzaussage"},
    { arabic: "الْمُبْتَدَأ", german: "Satzgegenstand"},
    { arabic: "تَـاُء مَرْبُـوطَـةٌ", german: "ة-Endung für Weibliche Substantive und Adjektive"},
    { arabic: "(أَلِف مَقْصُورَة (ى ", german: "Alif maqsūra"},
    { arabic: "نَعْتٌ", german: "Adjektiv"},
    { arabic: "مَنْعُوتٌ", german: "Substantiv"},
    { arabic: "اِسْمٌ مَوْصُولٌ", german: "Relativpronomen"},
    { arabic: "جُمْلَةُ صِلَةٍ", german: "Relativsatz" },
    { arabic: "مَنْصُوبٌ", german: "Akkusativ" },
  ]
  
};

/* ==========================================================================
   GLOSSAR-KATEGORIEN
   ==========================================================================
   Jedes Vokabelwort (in LESSONS, außer im Sonderblock "Grammatik") kann
   optional ein Feld "categories" bekommen — ein Array von Schlüsseln aus
   der Liste unten. Ein Wort kann in MEHREREN Kategorien gleichzeitig
   stehen, z. B. ein Relativpronomen, das gleichzeitig مبني (mabnī,
   indeklinabel) ist:

     { arabic: "الَّذِي", german: "der, welcher", categories: ["pronomen", "mabni"] }

   Ohne "categories"-Feld (oder mit leerem Array) gilt ein Wort im Glossar
   als "nicht zugeordnet". Die Zuordnung trägst du selbst nach und nach
   ein — nichts hier wurde automatisch vorbelegt.

   Neue Kategorien kannst du unten einfach ergänzen (Schlüssel frei wählbar,
   ar = arabischer Fachbegriff, de = deutsche Bezeichnung fürs Glossar).
*/
const CATEGORIES = {
  ism:            { ar: "اسْم",            de: "Nomen" },
  fiil:           { ar: "فِعْل",            de: "Verb" },
  harf:           { ar: "حَرْف",            de: "Partikel" },
  praeposition:   { ar: "حَرْفُ جَر",        de: "Präposition" },
  pronomen:       { ar: "ضَمِير",           de: "Pronomen" },
  ismmawsul:      { ar: "اِسْمٌ مَوْصُولٌ",     de: "Relativpronomen" },
  ismishara:      { ar: "اسْمُ إِشَارَة",      de: "Demonstrativpronomen" },
  mudaf:          { ar: "مُضَاف",           de: "Mudâf" },
  mudafilaihi:    { ar: "مُضَاف إِلَيْه",      de: "Mudâf ilaihi" },
  mubtada:        { ar: "مُبْتَدَأ",          de: "Mubtada (Satzgegenstand)" },
  khabar:         { ar: "خَبَر",            de: "Khabar (Satzaussage)" },
  naat:           { ar: "نَعْت",            de: "Na't (Adjektiv)" },
  manuut:         { ar: "مَنْعُوت",          de: "Man'ût (Substantiv zum Adjektiv)" },
  marfu:          { ar: "مَرْفُوع",          de: "Marfû' (Nominativ)" },
  majrur:         { ar: "مَجْرُور",          de: "Majrûr (Genitiv)" },
  mansub:         { ar: "مَنْصُوب",          de: "Mansûb (Akkusativ)" },
  marifa:         { ar: "مَعْرِفَة",          de: "Ma'rifa (bestimmt)" },
  nakira:         { ar: "نَكِرَة",           de: "Nakira (unbestimmt)" },
  mabni:          { ar: "مَبْنِي",           de: "Mabnī (indeklinabel)" },
};

const LESSON_LABELS = {
  1: "Lektion 1",
  2: "Lektion 2",
  3: "Lektion 3",
  4: "Lektion 4",
  5: "Lektion 5",
  6: "Lektion 6",
  7: "Lektion 7",
  8: "Lektion 8",
  9: "Lektion 9",
  10: "Lektion 10",
  11: "Lektion 11",
  12: "Lektion 12"
};