const LESSONS = {

  1: [
    { arabic: "بَيْتٌ", german: "ein Haus", categories: ["ism"] },
    { arabic: "مَسْجِدٌ", german: "eine Moschee", categories: ["ism"] },
    { arabic: "بَابٌ", german: "eine Tür", categories: ["ism"] },
    { arabic: "كِتَابٌ", german: "ein Buch", categories: ["ism"] },
    { arabic: "قَلَمٌ", german: "ein Stift", categories: ["ism"] },
    { arabic: "مِفْتَاحٌ", german: "ein Schlüssel", categories: ["ism"] },
    { arabic: "مَكْتَبٌ", german: "ein Schreibtisch, ein Burö (nach Lektion 7)", categories: ["ism"] },
    { arabic: "سَرِيرٌ", german: "ein Bett", categories: ["ism"] },
    { arabic: "كُرْسِيٌّ", german: "ein Stuhl", categories: ["ism"] },
    { arabic: "نَجْمٌ", german: "ein Stern", categories: ["ism"] },
    { arabic: "قَمِيصٌ", german: "ein Hemd", categories: ["ism"] },
    { arabic: "طَبِيبٌ", german: "ein Arzt", categories: ["ism"] },
    { arabic: "نَعَمْ", german: "ja", categories: ["harf", "mabni"] },
    { arabic: "أَ", german: "Fragepartikel (vor Entscheidungsfragen, direkt vor dem Folgewort)", categories: ["harf", "mabni"] },
    { arabic: "وَ", german: "und (direkt vor dem Folgewort)", categories: ["harf", "mabni"] },
    { arabic: "وَلَدٌ", german: "ein Junge", categories: ["ism"] },
    { arabic: "طَالِبٌ", german: "ein Student", categories: ["ism"] },
    { arabic: "رَجُلٌ", german: "ein Mann", categories: ["ism"] },
    { arabic: "تَاجِرٌ", german: "ein Händler", categories: ["ism"] },
    { arabic: "كَلْبٌ", german: "ein Hund", categories: ["ism"] },
    { arabic: "قِطٌّ", german: "ein Kater", categories: ["ism"] },
    { arabic: "حِمَارٌ", german: "ein Esel", categories: ["ism"] },
    { arabic: "حِصَانٌ", german: "ein Pferd", categories: ["ism"] },
    { arabic: "جَمَلٌ", german: "ein Kamel", categories: ["ism"] },
    { arabic: "دِيكٌ", german: "ein Hahn", categories: ["ism"] },
    { arabic: "مُدَرِّسٌ", german: "ein Lehrer", categories: ["ism"] },
    { arabic: "مِنْدِيلٌ", german: "ein Tuch (auch: Papiertaschentuch oder Serviette)", categories: ["ism"] },
    { arabic: "لَا", german: "nein", categories: ["harf", "mabni"] },
    { arabic: "مَا", german: "was", categories: ["ismistifham", "mabni"] },
  ],

  2: [
    { arabic: "إِمَامٌ", german: "ein Imam", categories: ["ism"] },
    { arabic: "سُكَّرٌ", german: "Zucker", categories: ["ism"] },
    { arabic: "حَجَرٌ", german: "ein Stein", categories: ["ism"] },
    { arabic: "لَبَنٌ", german: "eine Milch", categories: ["ism"] },
  ],

  3: [
    { arabic: "غَنِيٌّ", german: "reich", categories: ["ism"] },
    { arabic: "فَقِيرٌ", german: "arm", categories: ["ism"] },
    { arabic: "طَوِيلٌ", german: "groß (lang)", categories: ["ism"] },
    { arabic: "قَصِيرٌ", german: "kurz", categories: ["ism"] },
    { arabic: "بَارِدٌ", german: "kalt", categories: ["ism"] },
    { arabic: "حَارٌّ", german: "heiß", categories: ["ism"] },
    { arabic: "جَالِسٌ", german: "sitzend", categories: ["ism"] },
    { arabic: "وَاقِفٌ", german: "stehend", categories: ["ism"] },
    { arabic: "جَدِيدٌ", german: "neu", categories: ["ism"] },
    { arabic: "قَدِيمٌ", german: "alt", categories: ["ism"] },
    { arabic: "قَرِيبٌ", german: "nah", categories: ["ism"] },
    { arabic: "بَعِيدٌ", german: "fern", categories: ["ism"] },
    { arabic: "نَظِيفٌ", german: "sauber", categories: ["ism"] },
    { arabic: "وَسِخٌ", german: "schmutzig", categories: ["ism"] },
    { arabic: "صَغِيرٌ", german: "klein", categories: ["ism"] },
    { arabic: "كَبِيرٌ", german: "groß", categories: ["ism"] },
    { arabic: "خَفِيفٌ", german: "leicht (im Sinne des Gewichtes)", categories: ["ism"] },
    { arabic: "ثَقِيلٌ", german: "schwer", categories: ["ism"] },
    { arabic: "الْوَرَقُ", german: "das Papier", categories: ["ism"] },
    { arabic: "الْمَاءُ", german: "das Wasser", categories: ["ism"] },
    { arabic: "التُّفَاحُ", german: "die Äpfel", categories: ["ism"] },
    { arabic: "جَمِيلٌ", german: "schön", categories: ["ism"] },
    { arabic: "الدُّكَّانُ", german: "das Geschäft", categories: ["ism"] },
    { arabic: "حُلْوٌ", german: "süß", categories: ["ism"] },
    { arabic: "مَرِيضٌ", german: "krank", categories: ["ism"] },
    { arabic: "مكْسُوْرٌ", german: "kaputt, gebrochen", categories: ["ism"] },
    { arabic: "المهندس", german: "der Ingenieur", categories: ["ism"] },
    { arabic: "مُفْتاحٌ", german: "offen", categories: ["ism"] },
    { arabic: "لذيذٌ", german: "lecker", categories: ["ism"] },
    { arabic: "سَاعَةٌ ", german: "eine Uhr", categories: ["ism"] },
    { arabic: "تُفَّاحَةٌ ", german: "ein Apfel", categories: ["ism"] },
    { arabic: "التُّفَّاحَةُ ", german: "der Apfel", categories: ["ism"] },
  
  ],

  4: [
    { arabic: "أَيْنَ", german: "wo", categories: ["ismistifham", "mabni"] },
    { arabic: "عَلَى", german: "auf", categories: ["praeposition", "harf", "mabni"] },
    { arabic: "غُرْفَةٌ", german: "ein Zimmer", categories: ["ism"] },
    { arabic: "السَّمَاءُ", german: "der Himmel", categories: ["ism"] },
    { arabic: "الْحَمَّامُ", german: "das Badezimmer", categories: ["ism"] },
    { arabic: "الْفَصْلُ", german: "das Klassenzimmer", categories: ["ism"] },
    { arabic: "الْمَطْبَخُ", german: "die Küche", categories: ["ism"] },
    { arabic: "الْمِرْحَاضُ", german: "die Toilette", categories: ["ism"] },
    { arabic: "فِي", german: "in", categories: ["praeposition", "harf", "mabni"] },
    { arabic: "مِنْ", german: "von (wenn الـ nachfolgt, wird es zu مِنَ)", categories: ["praeposition", "harf", "mabni"] },
    { arabic: "إِلَى", german: "nach", categories: ["praeposition", "harf", "mabni"] },
    { arabic: "الْفِلِبِّينُ", german: "Philippinen", categories: ["ism"] },
    { arabic: "الْيَابَانُ", german: "Japan", categories: ["ism"] },
    { arabic: "الْمَدْرَسَةُ", german: "die Schule", categories: ["ism"] },
    { arabic: "الصِّينُ", german: "China", categories: ["ism"] },
    { arabic: "السُّوقُ", german: "der Markt", categories: ["ism"] },
    { arabic: "الْهِنْدُ", german: "Indien", categories: ["ism"] },
    { arabic: "الْجَامِعَةُ", german: "die Universität", categories: ["ism"] },
    { arabic: "الْمُدِيرُ", german: "der Direktor", categories: ["ism"] },
    { arabic: "ذَهَبَ", german: "Er ist gegangen", categories: ["fiil", "mabni"] },
    { arabic: "خَرَجَ", german: "Er ist hinaus gegangen", categories: ["fiil", "mabni"] }
  ],

  5: [
    { arabic: "الرَّسُولُ", german: "der Gesandte", categories: ["ism"] },
    { arabic: "تَحْتَ", german: "unter", categories: ["ism", "mudaf"] },
    { arabic: "الْعَمُّ", german: "der Onkel (Bruder des Vaters)", categories: ["ism"] },
    { arabic: "الِابْنُ", german: "der Sohn", categories: ["ism"] },
    { arabic: "الشَّارِعُ", german: "die Straße", categories: ["ism"] },
    { arabic: "السَّيَّارَةُ", german: "das Auto", categories: ["ism"] },
    { arabic: "الْكَعْبَةُ", german: "die Kaaba", categories: ["ism"] },
    { arabic: "هُنَا", german: "hier", categories: ["ismishara", "mabni"] },
    { arabic: "الْخَالُ", german: "der Onkel (Bruder der Mutter)", categories: ["ism"] },
    { arabic: "هُنَاكَ", german: "dort", categories: ["ismishara", "mabni"] },
    { arabic: "مُغْلَق", german: "verschlossen, geschlossen", categories: ["ism"] },
    { arabic: "الْبِنْتُ", german: "die Tochter, das Mädchen", categories: ["ism"] },
    { arabic: "الِاسْمُ", german: "der Name", categories: ["ism"] },
    { arabic: "الطَّبِيبُ", german: "der Arzt", categories: ["ism"] },
    { arabic: "الْحَقِيبَةُ", german: "die Tasche, der Rucksack", categories: ["ism"] },
  ],

  6: [
    { arabic: "يَدٌ", german: "eine Hand", categories: ["ism"] },
    { arabic: "رِجْلٌ", german: "ein Bein", categories: ["ism"] },
    { arabic: "عَيْنٌ", german: "ein Auge", categories: ["ism"] },
    { arabic: "أُذُنٌ", german: "ein Ohr", categories: ["ism"] },
    { arabic: "رَأْسٌ", german: "ein Kopf", categories: ["ism"] },
    { arabic: "أَنْفٌ", german: "eine Nase", categories: ["ism"] },
    { arabic: "فَمٌ", german: "ein Mund", categories: ["ism"] },
    { arabic: "وَجْهٌ", german: "ein Gesicht", categories: ["ism"] },
    { arabic: "الْمِكْوَاةُ", german: "das Bügeleisen", categories: ["ism"] },
    { arabic: "الْأَنْفُ", german: "die Nase", categories: ["ism"] },
    { arabic: "الْبَقَرَةُ", german: "die Kuh", categories: ["ism"] },
    { arabic: "الْفَمُ", german: "der Mund", categories: ["ism"] },
    { arabic: "الدَّرَّاجَةُ", german: "das Fahrrad", categories: ["ism"] },
    { arabic: "الْقِدْرُ", german: "der Kochtopf", categories: ["ism"] },
    { arabic: "الْمِلْعَقَةُ", german: "der Löffel", categories: ["ism"] },
    { arabic: "الْأُذُنُ", german: "das Ohr", categories: ["ism"] },
    { arabic: "الْفَلَّاحُ", german: "der Bauer", categories: ["ism"] },
    { arabic: "الْعَيْنُ", german: "das Auge", categories: ["ism"] },
    { arabic: "الْأُمُّ", german: "die Mutter", categories: ["ism"] },
    { arabic: "الْيَدُ", german: "die Hand", categories: ["ism"] },
    { arabic: "الْأَبُ", german: "der Vater", categories: ["ism"] },
    { arabic: "الرِّجْلُ", german: "das Bein", categories: ["ism"] },
    { arabic: "الثَّلَّاجَةُ", german: "der Kühlschrank", categories: ["ism"] },
    { arabic: "سَرِيعٌ", german: "schnell", categories: ["ism"] },
    { arabic: "الشَّايُ", german: "der Tee", categories: ["ism"] },
    { arabic: "النَّافِذَةُ", german: "das Fenster", categories: ["ism"] },
    { arabic: "الْمَغْرِبُ", german: "der Westen", categories: ["ism"] },
    { arabic: "الشَّرْقُ", german: "der Osten", categories: ["ism"] },
    { arabic: "الْقَهْوَةُ", german: "der Kaffee", categories: ["ism"] },
    { arabic: "أَيْضاً", german: "auch", categories: ["ism"] },
    { arabic: "جِدّاً", german: "sehr", categories: ["ism"] },
    { arabic: "لِمَنْ", german: "wessen oder wem gehört", categories: ["ismistifham", "mabni"] },
    { arabic: "لِـ", german: "gehören, besitzen, für", categories: ["praeposition", "harf", "mabni"] },
    { arabic: "شَمْسٌ ", german: "eine Sonne", categories: ["ism"] },
    { arabic: "مُسْلِمٌ ", german: "ein Muslim", categories: ["ism"] }
    ],

  7:[
    { arabic: "تِلْكَ", german: "das, jenes (weibliche Form von ذَلِكَ)", categories: ["ismishara", "mabni"] },
    { arabic: "النَّاقَةُ", german: "die Kamelstute", categories: ["ism"] },
    { arabic: "الْبَيْضَةُ", german: "das Ei", categories: ["ism"] },
    { arabic: "الْبَطَّةُ", german: "die Ente", categories: ["ism"] },
    { arabic: "الْمُؤَذِّنُ", german: "der Muezzin", categories: ["ism"] },
    { arabic: "الْمُمَرِّضَةُ", german: "die Krankenschwester", categories: ["ism"] },
    { arabic: "الدَّجَاجَةُ", german: "die Henne", categories: ["ism"] }
    ],

  8: [
    { arabic: "أَمْرِيكَا", german: "Amerika", categories: ["ism"] },
    { arabic: "السِّكِّينُ", german: "das Messer", categories: ["ism"] },
    { arabic: "مُغْلَقٌ", german: "geschlossen, verschlossen", categories: ["ism"] },
    { arabic: "أَلْمَانِيَا", german: "Deutschland", categories: ["ism"] },
    { arabic: "العِرَاقُ", german: "der Irak", categories: ["ism"] },
    { arabic: "إِنْكِلْتِرَا", german: "England", categories: ["ism"] },
    { arabic: "سُوِيسرَا", german: "Schweiz", categories: ["ism"] },
    { arabic: "المُسْتَشْفَى", german: "das Krankenhaus", categories: ["ism"] },
    { arabic: "خَلْفَ", german: "hinter", categories: ["ism", "mudaf"] },
    { arabic: "أَمَامَ", german: "vor", categories: ["ism", "mudaf"] },
    { arabic: "جَلَسَ", german: "er saß", categories: ["fiil", "mabni"] }
    ],

  9: [
    { arabic: "الفَاكِهَةُ", german: "das Obst", categories: ["ism"] },
    { arabic: "الإِنْكِلِيزِيَّةُ", german: "Englisch", categories: ["ism"] },
    { arabic: "العُصْفُورُ", german: "der Spatz (kleiner Vogel)", categories: ["ism"] },
    { arabic: "صَعْبٌ", german: "schwierig", categories: ["ism"] },
    { arabic: "الطَّائِرُ", german: "der Vogel (allgemein)", categories: ["ism"] },
    { arabic: "المَدِينَةُ", german: "die Stadt", categories: ["ism"] },
    { arabic: "العَرَبِيَّةُ", german: "Arabisch", categories: ["ism"] },
    { arabic: "القَاهِرَةُ", german: "Kairo", categories: ["ism"] },
    { arabic: "اللُّغَةُ", german: "die Sprache", categories: ["ism"] },
    { arabic: "اليَوْمَ", german: "heute", categories: ["ism"] },
    { arabic: "سَهْلٌ", german: "leicht (im Sinne der Komplextität)", categories: ["ism"] },
    { arabic: "لِمَاذَا", german: "warum", categories: ["ismistifham", "mabni"] },
    { arabic: "مُجْتَهِدٌ", german: "fleißig", categories: ["ism"] },
    { arabic: "الكُوبُ", german: "die Tasse, der Becher", categories: ["ism"] },
    { arabic: "شَهِيرٌ", german: "berühmt", categories: ["ism"] },
    { arabic: "الْمَكْتَبَةُ", german: "die Bücherei, der Buchladen", categories: ["ism"] },
    { arabic: "الثَّانَوِيَّةُ", german: "die Oberstufe, Oberschule", categories: ["ism"] },
    { arabic: "الآنَ", german: "jetzt", categories: ["ism", "mabni"] },
    { arabic: "الْوَزِيرُ", german: "der Minister", categories: ["ism"] },
    { arabic: "هُنَاكَ", german: "dort (hinten)", categories: ["ismishara", "mabni"] },
    { arabic: "حَادٌّ", german: "scharf (bei Klingen u. ä.)", categories: ["ism"] },
    { arabic: "الْمُسْتَوْصَفُ", german: "die Klinik, das kleine Krankenhaus", categories: ["ism"] },
    { arabic: "السُّوقُ", german: "der Markt", categories: ["ism"] },
    { arabic: "الْمِرْوَحَةُ", german: "der Ventilator", categories: ["ism"] },
    { arabic: "إِنْدُونِيسِيَا", german: "Indonesien", categories: ["ism"] },
    { arabic: "الْكُوَيْتُ", german: "Kuwait", categories: ["ism"] },
    { arabic: "الشَّارِعُ", german: "die Straße", categories: ["ism"] },
    { arabic: "عِنْدَ", german: "mit, bei", categories: ["ism", "mudaf"] },
    { arabic: "الَّذِي", german: "der, welcher", categories: ["ismmawsul", "mabni"] },
    { arabic: "فَرَنْسَا", german: "Frankreich", categories: ["ism"] },
    { arabic: "السَّبُّورَةُ", german: "die Tafel", categories: ["ism"] },
    { arabic: "الْمِحْرَابُ", german: "die Mihrab (Gebetsnische)", categories: ["ism"] },
    { arabic: "الْيَوْمُ", german: "der Tag", categories: ["ism"] },
    { arabic: "كَسْلَانُ", german: "faul", categories: ["ism"] },
    { arabic: "جَوْعَانُ", german: "hungrig", categories: ["ism"] },
    { arabic: "عَطْشَانُ", german: "durstig", categories: ["ism"] },
    { arabic: "غَضْبَانُ", german: "ärgerlich", categories: ["ism"] },
    { arabic: "مَلآنُ", german: "voll", categories: ["ism"] }
    ],

    10: [
      { arabic: "أَخُوكَ", german: "dein Bruder", categories: ["ism", "pronomen"] },
      { arabic: "كِتَابُكَ", german: "dein Buch", categories: ["ism", "pronomen"] },
      { arabic: "كِتَابُهُ", german: "sein Buch", categories: ["ism", "pronomen"] },
      { arabic: "كِتَابُهَا", german: "ihr Buch", categories: ["ism", "pronomen"] },
      { arabic: "كِتَابِي", german: "mein Buch", categories: ["ism", "pronomen"] },
      { arabic: "أَبُوهُ", german: "sein Vater", categories: ["ism", "pronomen"] },
      { arabic: "أَخِي", german: "mein Bruder", categories: ["ism", "pronomen"] },
      { arabic: "أَبِي", german: "mein Vater", categories: ["ism", "pronomen"] },
      { arabic: "لَكَ", german: "gehört dir", categories: ["praeposition", "pronomen", "mabni"] },
      { arabic: "لَهُ", german: "gehört ihm", categories: ["praeposition", "pronomen", "mabni"] },
      { arabic: "لَهَا", german: "gehört ihr", categories: ["praeposition", "pronomen", "mabni"] },
      { arabic: "لِي", german: "gehört mir", categories: ["praeposition", "pronomen", "mabni"] },
      { arabic: "ذَهَبْتُ", german: "ich ging", categories: ["fiil", "mabni"] },
      { arabic: "ذَهَبْتَ", german: "du gingst", categories: ["fiil", "mabni"] },
      { arabic: "مَعَ", german: "mit", categories: ["ism", "mudaf"] },
      { arabic: "بِ", german: "an, in", categories: ["praeposition", "harf", "mabni"] },
      { arabic: "بِالْجَامِعَةِ", german: "an der Universität", categories: ["praeposition", "ism"] },
      { arabic: "الزَّمِيلُ", german: "der Kollege, der Mitschüler", categories: ["ism"] },
      { arabic: "الفَتَى", german: "der junge Mann", categories: ["ism"] },
      { arabic: "الزَّوْجُ", german: "der Ehegatte", categories: ["ism"] },
      { arabic: "وَاحِدٌ", german: "eins", categories: ["ism"] },
      { arabic: "الطِفْلُ", german: "das Kind", categories: ["ism"] },
      { arabic: "مَا", german: "was, keine/nicht (als Verneinung)", categories: ["harf", "ismistifham", "mabni"] },
    ],

    11: [
      { arabic: "فِيهِ", german: "darin", categories: ["praeposition", "pronomen", "mabni"] },
      { arabic: "أُحِبُّ", german: "ich mag, ich liebe", categories: ["fiil"] },
      { arabic: "مَاذَا", german: "was (eindeutiges Fragewort, im Gegensatz zu مَا, das auch 'nicht' bedeuten kann)", categories: ["ismistifham", "mabni"] },
    ],

    12: [
      { arabic: "أَنْتِ", german: "du (weiblich)", categories: ["pronomen", "mabni"] },
      { arabic: "كِ", german: "besitzanzeigende Endung 'dein' bei weiblich Angesprochenen (Kasra, z. B. بَيْتُكِ)", categories: ["pronomen", "mabni"] },
      { arabic: "ذَهَبَتْ", german: "sie ging", categories: ["fiil", "mabni"] },
      { arabic: "الَّتِي", german: "die, welche (Relativpronomen, feminin Singular)", categories: ["ismmawsul", "mabni"] },
      { arabic: "الْعَمُّ", german: "der Onkel (väterlicherseits)", categories: ["ism"] },
      { arabic: "الشَّجَرَةُ", german: "der Baum", categories: ["ism"] },
      { arabic: "الْعَمَّةُ", german: "die Tante (väterlicherseits)", categories: ["ism"] },
      { arabic: "سُورِيَا", german: "Syrien", categories: ["ism"] },
      { arabic: "الْخَالُ", german: "der Onkel (mütterlicherseits)", categories: ["ism"] },
      { arabic: "الْمَدْرَسَةُ الْمُتَوَسِّطَةُ", german: "die Mittelschule", categories: ["ism"] },
      { arabic: "الْخَالَةُ", german: "die Tante (mütterlicherseits)", categories: ["ism"] },
      { arabic: "الْمُفَتِّشُ", german: "der Inspektor", categories: ["ism"] },
      { arabic: "مُسْتَشْفَى الْوِلَادَةِ", german: "das Entbindungsheim", categories: ["ism"] },
      { arabic: "الْفَتَاةُ", german: "die junge Frau", categories: ["ism"] },
      { arabic: "يَا سَيِّدِي", german: "mein Herr!"},
      { arabic: "الدَّفْتَرُ", german: "das Heft", categories: ["ism"] },
      { arabic: "يَا سَيِّدَتِي", german: "meine Dame!"},
      { arabic: "مَالِيزِيَا", german: "Malaysia", categories: ["ism"] },
      { arabic: "كَيْفَ حَالُكَ؟", german: "Wie geht es dir? / Wie geht es Ihnen?"},
      { arabic: "أَنَا بِخَيْرٍ", german: "Mir geht es gut."},
      { arabic: "أُمَّهَاتٌ", german: "Mütter (Plural von أُمٌّ)", categories: ["ism"] },
      { arabic: "آبَاءٌ", german: "Väter (Plural von أَبٌ)", categories: ["ism"] },
      { arabic: "وُزَرَاءُ", german: "Minister (Plural von وَزِيرٌ)", categories: ["ism"] },
      { arabic: "عُلَمَاءُ", german: "Gelehrte (Plural von عَالِمٌ)", categories: ["ism"] },
      { arabic: "أَقْوِيَاءُ", german: "Starke (Plural von قَوِيٌّ)", categories: ["ism"] },
      { arabic: "ضُعَفَاءُ", german: "Schwache (Plural von ضَعِيفٌ)", categories: ["ism"] },
      { arabic: "بَعْدَ", german: "nach (das folgende Substantiv steht im Genitiv)", categories: ["ism", "mudaf"] },
      { arabic: "الْمَمْلَكَةُ الْعَرَبِيَّةُ السُّعُودِيَّةُ", german: "das Königreich Saudi-Arabien", categories: ["ism"] },
    ],

  Grammatik: [
    { arabic: "تَنْوِين", german: "die Unbestimmtheit (hinsichtlich der Wortform)"},
    { arabic: "نَكِرَة", german: "unbestimmt (hinsichtlich der Grammatik)"},
    { arabic: "مَعْرِفَة", german: "bestimmt"},
    { arabic: "اسْمُ إِشَارَة", german: "Demonstrativpronomen"},
    { arabic: "مَعْرِفَة", german: "bestimmt"},
    { arabic: "لَامُ التَّعْرِيف", german: "die bestimmten Artikel"},
    { arabic: "جُمْلَة اسْمِيَّة" , german: "Nominalsatz"},
    { arabic: "حُرُوفُ الْجَر", german: "Präpositionen"},
    { arabic: "مَرْفُوع", german: "Nominativ"},
    { arabic: "مَجْرُور", german: "Genetiv"},
    { arabic: "اسْم", german: "Nomen"},
    { arabic: "فِعْل", german: "Verben"},
    { arabic: "حَرْف", german: "Partikel"},
    { arabic: "الْخَبَر", german: "Satzaussage"},
    { arabic: "الْمُبْتَدَأ", german: "Satzgegenstand"},
    { arabic: "تَـاُء مَرْبُـوطَـةٌ", german: "ة-Endung für Weibliche Substantive und Adjektive"},
    { arabic: "(أَلِف مَقْصُورَة (ى ", german: "Alif maqsūra"},
    { arabic: "نَعْتٌ", german: "Adjektiv"},
    { arabic: "مَنْعُوتٌ", german: "Substantiv"},
    { arabic: "اِسْمٌ مَوْصُولٌ", german: "Relativpronomen"},
    { arabic: "جُمْلَةُ صِلَةٍ", german: "Relativsatz" },
    { arabic: "مَنْصُوبٌ", german: "Akkusativ" },
  ]
  
};

/* ==========================================================================
   GLOSSAR-KATEGORIEN
   ==========================================================================
   Jedes Vokabelwort (in LESSONS, außer im Sonderblock "Grammatik") hat ein
   Feld "categories" — ein Array von Schlüsseln aus der Liste unten. Ein Wort
   kann in MEHREREN Kategorien gleichzeitig stehen, z. B. ein Relativpronomen,
   das zugleich مبني (mabnī, indeklinabel) ist:

     { arabic: "الَّذِي", german: "der, welcher", categories: ["ismmawsul", "mabni"] }

   Die Einteilung für Lektion 1–12 ist anhand des Madina-Buch-Schlüssels
   vorgenommen worden und kann jederzeit von Hand angepasst werden.

   Bewusst NICHT als Kategorien enthalten sind Begriffe, die keine Eigenschaft
   des Wortes selbst sind, sondern von seiner Stellung im Satz abhängen:
   Mubtada, Khabar, Na't, Man'ût, Mudâf ilaihi sowie Marfû'/Majrûr/Mansûb.
   (Nakira/Ma'rifa ergeben sich aus Tanwîn bzw. ال und stehen schon im Wort.)

   "mudaf" markiert nur Wörter, die IMMER als Mudâf stehen (Ẓuruf wie خَلْفَ,
   أَمَامَ, تَحْتَ, عِنْدَ, مَعَ, بَعْدَ — das Folgewort ist ihr Mudâf ilaihi).

   Feste Wendungen und ganze Sätze (z. B. يَا سَيِّدِي, كَيْفَ حَالُكَ؟) haben
   keine Kategorie und erscheinen im Glossar unter "Nicht zugeordnet".

   Neue Kategorien kannst du unten einfach ergänzen (Schlüssel frei wählbar,
   ar = arabischer Fachbegriff, de = deutsche Bezeichnung fürs Glossar).
   Die Reihenfolge hier bestimmt die Reihenfolge im Glossar.
*/
const CATEGORIES = {
  fiil:           { ar: "فِعْل",            de: "Verb" },
  praeposition:   { ar: "حَرْفُ جَرّ",       de: "Präposition" },
  harf:           { ar: "حَرْف",            de: "Partikel" },
  pronomen:       { ar: "ضَمِير",           de: "Pronomen" },
  ismishara:      { ar: "اسْمُ إِشَارَة",      de: "Demonstrativpronomen" },
  ismmawsul:      { ar: "اِسْمٌ مَوْصُولٌ",     de: "Relativpronomen" },
  ismistifham:    { ar: "اِسْمُ اسْتِفْهَام",   de: "Fragewort" },
  mudaf:          { ar: "مُضَاف",           de: "Mudâf (steht immer als Mudâf)" },
  mabni:          { ar: "مَبْنِي",           de: "Mabnī (indeklinabel)" },
  ism:            { ar: "اسْم",            de: "Nomen (inkl. Adjektive und Namen)" },
};

const LESSON_LABELS = {
  1: "Lektion 1",
  2: "Lektion 2",
  3: "Lektion 3",
  4: "Lektion 4",
  5: "Lektion 5",
  6: "Lektion 6",
  7: "Lektion 7",
  8: "Lektion 8",
  9: "Lektion 9",
  10: "Lektion 10",
  11: "Lektion 11",
  12: "Lektion 12"
};